console.log("Hello daddy");
console.log("Goodbye cold World");
console.log("Come on to this tragic affair");
console.log("Im just a poor boy");
console.log("How long how long?");
console.log("Oops I did it again");
console.log("Hello my love");
console.log("The truth is that I never shoot my shadow");
console.log("Kuroi namida");
console.log("Chikorita");